server:
  port: 8001
  servlet:
    context-path: /ai-meeting
spring:
  application:
    name: ai-meeting
  datasource:
    url: jdbc:mysql://106.54.58.237:3306/meeting_ai?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: cuijian
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev

# MyBatis-Flex配置
mybatis-flex:
  mapper-locations: classpath:mapper/*.xml  # 可选，如需自定义SQL
  configuration:
    map-underscore-to-camel-case: true  # 下划线转驼峰

langchain4j:
  open-ai:
    chat-model:
      api-key: sk-407705c4dfb349af8900df352ada77e8
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      base-url:  https://api.deepseek.com
      max-tokens: 8192
      max-retries: 3
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-407705c4dfb349af8900df352ada77e8
      model-name: deepseek-chat
      max-tokens: 8192
      log-requests: true
      log-responses: true